### ISSUE TITLE
JOSE Review ToDo

### ISSUE THREAD

**Issue by PedroVelez** [euroargodev/argoonlineschool#17]
List of ToDo things before submitting to JOSE:

- [x] verify folder image of the ./Data folder and 'HowTodoDownloadTheData'
- [x] add and explanation in L03 of how to download a snapshot of the Argo data set and how useful it is for reproducible science.
- [x] Define CTD and the begging of the school, when we define a 'profile'
- [x] Upload all the videos to YouTube with a cover for each ones
- [x] L1
- [x] L2
- [x] L3
- [x] L2C10, expand explanation of the Link to satellite Jason
- [x] Add one sentences before each video.
- [x] Update sst.day.mean.2019.nc to sst.day.mean.2020.nc and all the metions to it
- [x] Renumber chapters in L1 to have 101, 102.... (LCnumberOfVideo) since now we jump from 101 to 121  
- [x] the same for L2
- [x] the same for L3 
- [x] Update /sst.day.mean.2019.nc to sst.day.mean.2020.nc and the image associated
- [x] Modify requirementes.txt to create new enviroment, use conda install numpy=1.26.4
